### ISSUE TITLE
MNI transform directory name in fmriprep workdir for collect_fmriprep() function?

### ISSUE THREAD

**Issue by mckenziephagen** [ME-ICA/tedana-reliability-analysis#10]
I'm trying to gather files from my fmriprep work directory so that I can combine them, and continue pre-processing using collect_fmriprep.py, but it seems that my run of fmriprep20.1.1 did not generate those files - has the names of these directories possibly been changed in newer versions of fmriprep? 

It's possible that my run of fmriprep just didn't generate these files, but I think that's unlikely because my reports appear to be complete, and I didn't get any errors in my run. 

fMRIPrep command: 
```/usr/local/miniconda/bin/fmriprep /data /data/derivatives/fmriprep-20.1.1 participant --participant-label tst312 -w /work/ -vv --omp-nthreads 8 --nthreads 12 --mem_mb 30000 --output-spaces MNI152NLin2009cAsym:res-2 anat fsnative fsaverage5 --fs-subjects-dir /fsdir```

Thanks!

**Comment by mckenziephagen** [comment]
Update on this - it appears that this is the case, and that the proper files are no longer at the path specified, as confirmed by Chris Markiewicz's response to gspitz below. 

https://neurostars.org/t/combining-fmriprep-with-me-ica-from-tedana/3710/14

I've forked the repo and am happy to contribute a PR when I've found all the necessary files and successfully applied them as validation. I'm not sure how frequently these are renamed and moved in new versions of fmriprep, but it seems that it's been stable across at least a couple releases at this point.

**Comment by tsalo** [comment]
That would be really great, thank you! We haven't touched this repository in a while, and fMRIPrep's working directories are prone to change from release to release. We could also follow up with fMRIPrep about outputting the reference image to structural transform, since the structural to template transform is already outputted I think. That way, we'd just need to track down the echo-wise data in reference image space from the working directory instead of both that _and_ the transform.

**Comment by tsalo** [comment]
I came across a closed issue in fMRIPrep that is probably relevant (https://github.com/poldracklab/fmriprep/issues/2189). @JulioAPeraza might also be willing and able to help with this.

**Comment by tsalo** [comment]
Oh and here's another (open) issue requesting the transform be added to the output directory, https://github.com/poldracklab/fmriprep/issues/1184, in case that's something you'd be willing to target.

**Comment by mckenziephagen** [comment]
Oh, thanks! I'll look into that after adapting this code, and then I can return to this code and make it more flexible, just so that my immediate projects can continue to move forward instead of stalling. 

I was also wondering what the intention with collect_xform() was... it seems like the author was trying to collect the xforms seperate from collect_fmriprep(), but I don't see a strong rationale for either option, and don't want to branch away from the original author's intentions in case there was a good reason for one or the other.

**Comment by tsalo** [comment]
`collect_xform()` was supposed to grab all of the separate transforms so they could be applied in a single shot, but I never got it working. I think `collect_fmriprep()` is just meant to find and copy the transform files to the output directory as needed, without applying them.

**Comment by tsalo** [comment]
I've opened a PR to output the xform (https://github.com/poldracklab/fmriprep/pull/2233). If it gets merged, there will still be the issue of collecting the relevant native reference-space BOLD files, but it should help.

**Comment by JulioAPeraza** [comment]
> I've opened a PR to output the xform (poldracklab/fmriprep#2233).

Thank you @tsalo, that is great.

> there will still be the issue of collecting the relevant native reference-space BOLD files.

Indeed

Just one detail. If susceptibility distortion correction (SDC) was applied you will need to collect uncorrected files for [tedana](https://tedana.readthedocs.io/en/latest/usage.html#perform-distortion-correction-spatial-normalization-smoothing-and-any-rescaling-or-filtering-after-tedana). 
The ones collected by `collect_fmriprep.py` : 
```
path/to/scratch/fmriprep_wf/single_subject_<...>_wf/func_preproc_ses_<...>_task_<...>_echo_1_wf/bold_bold_trans_wf/_bold_file_..data..sub-<...>..ses-<...>..func..sub-<...>_ses-<...>_task-<...>_echo-<1-3>_bold.nii.gz/merge/vol0000_xform-00000_merged.nii.gz.
```
would be SDCed.

I think fMRIPrep corrects head motion and susceptibility distortions with a composite transformation. Check this: 
```
path/to/scratch/fmriprep_wf/single_subject_<...>_wf/func_preproc_ses_<...>_task_<...>_echo_1_wf/bold_bold_trans_wf/_bold_file_..data..sub-<...>..ses-<...>..func..sub-<...>_ses-<...>_task-<...>_echo-<1-3>_bold.nii.gz/bold_transform/command.txt
```
So you will need to add another conditional to your code and collect the split files from 
```
path/to/scratch/fmriprep_wf/single_subject_<...>_wf/func_preproc_ses_<...>_task_<...>_echo_1_wf/_bold_file_..data..sub-<...>..ses-<...>..func..sub-<...>_ses-<...>_task-<...>_echo-<1-3>_bold.nii.gz/bold_split/vol*.nii.gz
```
apply only the head motion correction 
```
path/to/scratch/fmriprep_wf/single_subject_<...>_wf/func_preproc_ses_<...>_task_<...>_echo_1_wf/bold_hmc_wf/fsl2itk/mat2itk.txt
```
and merge the images.

A general transformation to your code would be:

```
tedanaOutput = path/to/tedana-mdl-0.0.9a1/sub-<...>/ses-<...>/<...>/dn_ts_OC.nii.gz
tedanaOutputMNI = path/to/fmriprep-20.1.1/fmriprep/sub-<...>/ses-<...>/func/sub-<...>_ses-<...>_task-<...>_space-MNI152NLin2009cAsym_res-2_desc-MEICAmdl_bold.nii.gz
reference = $HOME/.cache/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T1w.nii.gz
warp = path/to/scratch/fmriprep_wf/single_subject_<...>_wf/func_preproc_ses_<...>_task_<...>_echo_1_wf/sdc_estimate_wf/pepolar_unwarp_wf/cphdr_warp/_warpfieldQwarp_PLUS_WARP_fixhdr.nii.gz
scan2T1w = path/to/scratch/fmriprep_wf/single_subject_<...>_wf/func_preproc_ses_<...>_task_<...>_echo_1_wf/bold_reg_wf/bbreg_wf/concat_xfm/out_fwd.tfm
T1w2MNI = path/to/fmriprep-20.1.1/fmriprep/sub-<...>/anat/sub-<...>_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5

antsApplyTransforms --dimensionality 3 \
	--input-image-type 3 \
	--input ${tedanaOutput} \
	--default-value 0 \
	--float 1 \
	--interpolation LanczosWindowedSinc \
	--output ${tedanaOutputMNI} \
	--reference-image ${reference} \
	--transform ${T1w2MNI} \
	--transform ${scan2T1w} \
	--transform ${warp} \
	--verbose 1
```

If you do not perform SDC, you won't need `--transform ${warp}`.

That is the way I did it, but I might be missing something.

**Comment by tsalo** [comment]
That's true, thanks for catching it. Do you want to open a PR to update `collect_fmriprep()`? That might make things easier for @mckenziephagen as well.

**Comment by JulioAPeraza** [comment]
> Do you want to open a PR to update `collect_fmriprep()`? 

Yes, I am happy to do it.

**Comment by tsalo** [comment]
It'll be dependent on my new fMRIPrep PR though, so you might want to wait to work on it until after that's merged.

**Comment by tsalo** [comment]
Now that the new PR's merged, you can move forward with this. The transforms are named like this:

```
sub-<subject_label>_[specifiers]_from-scanner_to-T1w_mode-image_xfm.txt
sub-<subject_label>_[specifiers]_from-T1w_to-scanner_mode-image_xfm.txt
```
